using System;

namespace CollabTool.Web.Models
{
	/// <summary>
	/// Represents a note object stored as part of student custom data in the inBloom custom data store
	/// </summary>
	public class Note
	{
		public Note()
		{
			// Defaults
			Id = Guid.NewGuid();
			DateTime = DateTime.UtcNow;
		}

		/// <summary>
		/// Internal ID generated by the CollabApp system for this note
		/// </summary>
		public Guid Id { get; set; }

		/// <summary>
		/// The student ID
		/// </summary>
		public string StudentId { get; set; }

		/// <summary>
		/// The note subject
		/// </summary>
		public string Subject { get; set; }

		/// <summary>
		/// The main note text
		/// </summary>
		public string Text { get; set; }

		/// <summary>
		/// Date and time that the note was saved
		/// </summary>
		public DateTime DateTime { get; set; }

		/// <summary>
		/// The User ID of the teacher
		/// </summary>
		public string TeacherId { get; set; }

		/// <summary>
		/// The name of the teacher who made the note
		/// </summary>
		public string TeacherName { get; set; }

		/// <summary>
		/// The type of note being saved
		/// Eg. "Compliment" or  "Comment"
		/// Note, these values are fixed from the UI but stored as text in the inBloom data store
		/// </summary>
		public string NoteType { get; set; }

		/// <summary>
		/// Boolean value specifying whether an email notification was sent
		/// </summary>
		public bool EmailNotificationSent { get; set; }

		/// <summary>
		/// List of recipients to whom the email notification was sent
		/// </summary>
		public string[] EmailRecipients { get; set; }
	}
}