using System;

namespace CollabTool.Web.Models
{
	/// <summary>
	/// Represents a note object stored as part of student custom data in the inBloom custom data store
	/// </summary>
	public class Note
	{
		public Note()
		{
			// Generate Id
			Id = Guid.NewGuid();
		}

		/// <summary>
		/// Internal ID generated by the CollabApp system for this note
		/// </summary>
		public Guid Id { get; set; }

		/// <summary>
		/// Date and time that the note was saved
		/// </summary>
		public DateTime DateTime { get; set; }

		/// <summary>
		/// The User ID of the teacher
		/// </summary>
		public string TeacherId { get; set; }

		/// <summary>
		/// The type of note being saved
		/// Eg. "Behavior", "Peformance", etc
		/// Note, these values are fixed from the UI but stored as text in the inBloom data store
		/// </summary>
		public string NoteType { get; set; }
		
		/// <summary>
		/// Boolean value specifying whether an email notification was sent
		/// </summary>
		public bool SentEmail { get; set; }
		
		/// <summary>
		/// List of recipients to whom the email notification was sent
		/// </summary>
		public string[] EmailRecipients { get; set; }
		
		/// <summary>
		/// Sentiment type specifying the mood of the note
		/// ie. Is it something positive, negative or neutral
		/// </summary>
		public SentimentType SentimentType { get; set; }
	}

	/// <summary>
	/// Represents the sentiment type of a message
	/// </summary>
	public enum SentimentType
	{
		/// <summary>
		/// Neutral; message is informative only
		/// </summary>
		Neutral = 0,

		/// <summary>
		/// Positive; note is about something positive that the student said or done
		/// </summary>
		Positive = 1,

		/// <summary>
		/// Negative; note is about something negative that the student said or done
		/// </summary>
		Negative = 2,
	}
}